# Generated by Django 4.0.1 on 2022-01-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstQue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1Q', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SecondQue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_2Q', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdQue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_3Q', models.CharField(max_length=20)),
            ],
        ),
    ]
