# Generated by Django 4.0.1 on 2022-01-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('que', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstque',
            old_name='user_1Q',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='secondque',
            old_name='user_2Q',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='thirdque',
            old_name='user_3Q',
            new_name='user_name',
        ),
    ]
